<?php

namespace TeamNiftyGmbH\Shopware\Dto;

use Spatie\LaravelData\Data as SpatieData;

/**
 * Added since version: 6.0.0.0
 */
class Customer extends SpatieData
{
    public function __construct(
        public ?string $id = null,
        public ?string $groupId = null,
        public ?string $salesChannelId = null,
        public ?string $languageId = null,
        public ?string $lastPaymentMethodId = null,
        public ?string $defaultBillingAddressId = null,
        public ?string $defaultShippingAddressId = null,
        public ?int $autoIncrement = null,
        public ?string $customerNumber = null,
        public ?string $salutationId = null,
        public ?string $firstName = null,
        public ?string $lastName = null,
        public ?string $email = null,
        public ?string $title = null,
        public ?string $affiliateCode = null,
        public ?string $campaignCode = null,
        public ?bool $active = null,
        public ?bool $doubleOptInRegistration = null,
        public ?string $doubleOptInEmailSentDate = null,
        public ?string $doubleOptInConfirmDate = null,
        public ?string $hash = null,
        public ?bool $guest = null,
        public ?string $firstLogin = null,
        public ?string $lastLogin = null,
        public ?string $birthday = null,
        public ?string $lastOrderDate = null,
        public ?int $orderCount = null,
        public ?float $orderTotalAmount = null,
        public ?int $reviewCount = null,
        public ?object $customFields = null,
        public ?string $remoteAddress = null,
        public ?array $tagIds = null,
        public ?string $requestedGroupId = null,
        public ?string $boundSalesChannelId = null,
        public ?string $createdById = null,
        public ?string $updatedById = null,
        public ?string $createdAt = null,
        public ?string $updatedAt = null,
        public ?CustomerGroup $group = null,
        public ?SalesChannel $salesChannel = null,
        public ?Language $language = null,
        public ?PaymentMethod $lastPaymentMethod = null,
        public ?CustomerAddress $defaultBillingAddress = null,
        public ?CustomerAddress $activeBillingAddress = null,
        public ?CustomerAddress $defaultShippingAddress = null,
        public ?CustomerAddress $activeShippingAddress = null,
        public ?Salutation $salutation = null,
        public ?array $addresses = null,
        public ?array $orderCustomers = null,
        public ?array $tags = null,
        public ?array $promotions = null,
        public ?array $productReviews = null,
        public ?CustomerRecovery $recoveryCustomer = null,
        public ?CustomerGroup $requestedGroup = null,
        public ?SalesChannel $boundSalesChannel = null,
        public ?array $wishlists = null,
        public ?User $createdBy = null,
        public ?User $updatedBy = null,
        public ?string $defaultPaymentMethodId = null,
        public ?string $company = null,
        public ?string $vatIds = null,
        public ?string $accountType = null,
    ) {}
}
