<?php

namespace TeamNiftyGmbH\Shopware\Dto;

use Spatie\LaravelData\Data as SpatieData;

/**
 * Added since version: 6.0.0.0
 */
class Product extends SpatieData
{
    public function __construct(
        public ?string $id = null,
        public ?string $versionId = null,
        public ?string $parentId = null,
        public ?string $parentVersionId = null,
        public ?string $manufacturerId = null,
        public ?string $productManufacturerVersionId = null,
        public ?string $unitId = null,
        public ?string $taxId = null,
        public ?string $coverId = null,
        public ?string $productMediaVersionId = null,
        public ?string $deliveryTimeId = null,
        public ?string $featureSetId = null,
        public ?string $canonicalProductId = null,
        public ?string $canonicalProductVersionId = null,
        public ?string $cmsPageId = null,
        public ?string $cmsPageVersionId = null,
        public ?array $price = null,
        public ?string $productNumber = null,
        public ?int $restockTime = null,
        public ?int $autoIncrement = null,
        public ?bool $active = null,
        public ?bool $available = null,
        public ?bool $isCloseout = null,
        public ?int $availableStock = null,
        public ?int $stock = null,
        public ?array $variation = null,
        public ?string $displayGroup = null,
        public ?object $variantListingConfig = null,
        public ?object $variantRestrictions = null,
        public ?string $manufacturerNumber = null,
        public ?string $ean = null,
        public ?int $purchaseSteps = null,
        public ?int $maxPurchase = null,
        public ?int $minPurchase = null,
        public ?float $purchaseUnit = null,
        public ?float $referenceUnit = null,
        public ?bool $shippingFree = null,
        public ?array $purchasePrices = null,
        public ?bool $markAsTopseller = null,
        public ?float $weight = null,
        public ?float $width = null,
        public ?float $height = null,
        public ?float $length = null,
        public ?string $releaseDate = null,
        public ?float $ratingAverage = null,
        public ?array $categoryTree = null,
        public ?array $propertyIds = null,
        public ?array $optionIds = null,
        public ?array $streamIds = null,
        public ?array $tagIds = null,
        public ?array $categoryIds = null,
        public ?int $childCount = null,
        public ?bool $customFieldSetSelectionActive = null,
        public ?int $sales = null,
        public ?string $metaDescription = null,
        public ?string $name = null,
        public ?string $keywords = null,
        public ?string $description = null,
        public ?string $metaTitle = null,
        public ?string $packUnit = null,
        public ?string $packUnitPlural = null,
        public ?object $customFields = null,
        public ?object $slotConfig = null,
        public ?array $customSearchKeywords = null,
        public ?string $type = null,
        public ?array $states = null,
        public ?string $createdAt = null,
        public ?string $updatedAt = null,
        public ?object $translated = null,
        public ?array $downloads = null,
        public ?Product $parent = null,
        public ?array $children = null,
        public ?DeliveryTime $deliveryTime = null,
        public ?Tax $tax = null,
        public ?ProductManufacturer $manufacturer = null,
        public ?Unit $unit = null,
        public ?ProductMedia $cover = null,
        public ?ProductFeatureSet $featureSet = null,
        public ?CmsPage $cmsPage = null,
        public ?Product $canonicalProduct = null,
        public ?array $prices = null,
        public ?array $media = null,
        public ?array $crossSellings = null,
        public ?array $crossSellingAssignedProducts = null,
        public ?array $configuratorSettings = null,
        public ?array $visibilities = null,
        public ?array $searchKeywords = null,
        public ?array $productReviews = null,
        public ?array $mainCategories = null,
        public ?array $seoUrls = null,
        public ?array $orderLineItems = null,
        public ?array $wishlists = null,
        public ?array $options = null,
        public ?array $properties = null,
        public ?array $categories = null,
        public ?array $streams = null,
        public ?array $categoriesRo = null,
        public ?array $tags = null,
        public ?array $customFieldSets = null,
    ) {}
}
