<?php

namespace TeamNiftyGmbH\Shopware\Dto;

use Spatie\LaravelData\Data as SpatieData;

/**
 * Added since version: 6.0.0.0
 */
class SalesChannel extends SpatieData
{
	public function __construct(
		public ?string $id = null,
		public ?string $typeId = null,
		public ?string $languageId = null,
		public ?string $customerGroupId = null,
		public ?string $currencyId = null,
		public ?string $paymentMethodId = null,
		public ?string $shippingMethodId = null,
		public ?string $countryId = null,
		public ?string $analyticsId = null,
		public ?string $navigationCategoryId = null,
		public ?string $navigationCategoryVersionId = null,
		public ?int $navigationCategoryDepth = null,
		public ?string $footerCategoryId = null,
		public ?string $footerCategoryVersionId = null,
		public ?string $serviceCategoryId = null,
		public ?string $serviceCategoryVersionId = null,
		public ?string $mailHeaderFooterId = null,
		public ?string $hreflangDefaultDomainId = null,
		public ?MeasurementUnits $measurementUnits = null,
		public ?string $name = null,
		public ?string $shortName = null,
		public ?string $taxCalculationType = null,
		public ?string $accessKey = null,
		public ?object $configuration = null,
		public ?bool $active = null,
		public ?bool $hreflangActive = null,
		public ?bool $maintenance = null,
		public ?array $maintenanceIpWhitelist = null,
		public ?object $customFields = null,
		public ?array $paymentMethodIds = null,
		public ?string $homeCmsPageId = null,
		public ?string $homeCmsPageVersionId = null,
		public ?object $homeSlotConfig = null,
		public ?bool $homeEnabled = null,
		public ?string $homeName = null,
		public ?string $homeMetaTitle = null,
		public ?string $homeMetaDescription = null,
		public ?string $homeKeywords = null,
		public ?string $createdAt = null,
		public ?string $updatedAt = null,
		public ?object $translated = null,
		public ?object $extensions = null,
		public ?array $currencies = null,
		public ?array $languages = null,
		public ?array $countries = null,
		public ?array $paymentMethods = null,
		public ?array $shippingMethods = null,
		public ?SalesChannelType $type = null,
		public ?Language $language = null,
		public ?CustomerGroup $customerGroup = null,
		public ?Currency $currency = null,
		public ?PaymentMethod $paymentMethod = null,
		public ?ShippingMethod $shippingMethod = null,
		public ?Country $country = null,
		public ?array $orders = null,
		public ?array $customers = null,
		public ?CmsPage $homeCmsPage = null,
		public ?array $domains = null,
		public ?array $systemConfigs = null,
		public ?Category $navigationCategory = null,
		public ?Category $footerCategory = null,
		public ?Category $serviceCategory = null,
		public ?array $productVisibilities = null,
		public ?SalesChannelDomain $hreflangDefaultDomain = null,
		public ?MailHeaderFooter $mailHeaderFooter = null,
		public ?array $newsletterRecipients = null,
		public ?array $numberRangeSalesChannels = null,
		public ?array $promotionSalesChannels = null,
		public ?array $documentBaseConfigSalesChannels = null,
		public ?array $productReviews = null,
		public ?array $seoUrls = null,
		public ?array $seoUrlTemplates = null,
		public ?array $mainCategories = null,
		public ?array $productExports = null,
		public ?SalesChannelAnalytics $analytics = null,
		public ?array $customerGroupsRegistrations = null,
		public ?array $landingPages = null,
		public ?array $boundCustomers = null,
		public ?array $wishlists = null,
	) {
	}
}
