<?php

namespace TeamNiftyGmbH\Shopware\Requests\DocumentManagement;

use Saloon\Enums\Method;
use Saloon\Http\Request;
use Saloon\Http\Response;

/**
 * numberRangeReserve
 *
 * This endpoint provides functionality to reserve or preview a document number which can be used to
 * create a new document using the `/_action/order/{orderId}/document/{documentTypeName}`
 * endpoint.
 *
 * The number generated by the endpoint will be reserved and the number pointer will be
 * incremented with every call. For preview purposes, you can add the `?preview=1` parameter to the
 * request. In that case, the number will not be incremented.
 */
class NumberRangeReserve extends Request
{
    protected Method $method = Method::GET;

    public function resolveEndpoint(): string
    {
        return "/_action/number-range/reserve/{$this->type}/{$this->saleschannel}";
    }

    /**
     * @param  string  $type  `technicalName` of the document type (e.g. `document_invoice`). Available types can be fetched with the `/api/document-type endpoint`.
     * @param  string  $saleschannel  Sales channel for the number range. Number ranges can be defined per sales channel, so you can pass a sales channel ID here.
     * @param  null|bool  $preview  If this parameter has a true value, the number will not actually be incremented, but only previewed.
     */
    public function __construct(
        protected string $type,
        protected string $saleschannel,
        protected ?bool $preview = null,
    ) {}

    public function defaultQuery(): array
    {
        return array_filter(['preview' => $this->preview]);
    }

    public function createDtoFromResponse(Response $response): mixed
    {
        return $response->json();
    }
}
