name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: read

jobs:
  tests:
    runs-on: [self-hosted, Linux]
    container:
      image: ghcr.io/team-nifty-gmbh/flux-ci:php${{ matrix.php }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        php: [8.3, 8.4, 8.5]

    name: PHP ${{ matrix.php }}

    steps:
      - uses: actions/checkout@v5

      - name: Fix git ownership
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run Tests
        run: vendor/bin/pest
